# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://xgubbnhhcfosnylqhlfk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndWJibmhoY2Zvc255bHFobGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg3OTcyMzMsImV4cCI6MjAyNDM3MzIzM30.esJn6d1Frk9myp-11ZTjigfAPk5cuwF6l7m1o14Ly58"